import turtle
turtle.speed(10)
turtle.pencolor('white')
turtle.right(90)
turtle.forward(200)
turtle.left(90)
turtle.pencolor('blue')
turtle.pensize(5)
turtle.circle(225)
turtle.left(90)
for i in range(24):
    turtle.forward(225)
    turtle.right(165)
    turtle.forward(225)
    turtle.left(180)
turtle.forward(80)
turtle.done()
