import turtle
turtle.speed(10)
turtle.bgcolor('white')
turtle.penup()
turtle.goto(-330,250)
turtle.pendown()
turtle.right(90)
color = ['orange','white','green']
for i in range(3):
    turtle.pencolor(color[i])
    turtle.fillcolor(color[i])
    turtle.begin_fill()
    turtle.forward(150)
    turtle.left(90)
    turtle.forward(650)
    turtle.left(90)
    turtle.forward(150)
    turtle.left(90)
    turtle.forward(650)
    turtle.left(90)
    turtle.forward(150)
    turtle.end_fill()
turtle.back(150)
turtle.left(90)
turtle.forward(325)
turtle.pencolor('blue')
turtle.pensize(2.5)
turtle.circle(75)
turtle.left(90)
for i in range(24):
    turtle.forward(75)
    turtle.right(165)
    turtle.forward(75)
    turtle.left(180)
turtle.forward(80)
turtle.done()
